name: Flutter WEB CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - run: apt-get update && apt-get install xz-utils
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev' # or: 'dev' or 'beta'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: fourier-circles-release-${{ github.sha }}
        path: build/web
